name: test workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          gh release list --repo leanprover/lean4 --limit 1
          exit 0
        env:
          GH_TOKEN: ${{ github.token }}